CREATE TABLE TECH_SCHEMA.SKILLS_CERTIFICATION (
    SKILL_ID NUMBER(22) NOT NULL,
    SKILL_NAME VARCHAR2(200) NOT NULL,
    SKILL_CATEGORY VARCHAR2(100) NOT NULL, -- 'PROGRAMMING', 'DATABASE', 'NETWORKING', 'PROJECT MANAGEMENT', 'CLOUD'
    SKILL_LEVEL VARCHAR2(50) NULL, -- 'BEGINNER', 'INTERMEDIATE', 'ADVANCED', 'EXPERT'
    DESCRIPTION VARCHAR2(500) NULL,
    IS_CERTIFICATION VARCHAR2(1) DEFAULT 'N' NOT NULL, -- 'Y' or 'N'
    CERTIFICATION_PROVIDER VARCHAR2(100) NULL,
    CERTIFICATION_CODE VARCHAR2(50) NULL,
    VALIDITY_PERIOD NUMBER(5) NULL, -- in months
    RENEWAL_REQUIRED VARCHAR2(1) DEFAULT 'N' NULL, -- 'Y' or 'N'
    REQUIRED_TRAINING_ID NUMBER(22) NULL, -- Link to TRAINING table if applicable
    MARKET_VALUE NUMBER(10,2) NULL, -- estimated market value of the skill
    PRIORITY_LEVEL NUMBER(1) DEFAULT 3 NULL, -- 1-5 with 1 being highest priority
    STATUS VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL, -- 'ACTIVE', 'INACTIVE', 'DEPRECATED'
    CREATED_BY VARCHAR2(50) NULL,
    CREATED_DATE DATE DEFAULT SYSDATE NOT NULL,
    UPDATED_BY VARCHAR2(50) NULL,
    UPDATED_DATE DATE NULL
);
commit;